package org.example.connection.states;

public enum ConnectionStatusE {
    TRY_HANDSHAKE, SERVER_HANDSHAKE, SEND_UNCHOKE, SEND_BITSET, SEND_HAVE, LOAD_SERVER_DATA, READY_SEND_SEG,
    LISTENER_ID, LISTENER_DATA, LISTENER_LENGTH, CONNECTED, INTERESTED, REQUESTED, DISCONNECTED,
    LOAD_DATA, WAIT_TASK
}
